# Install packages for Debian
---
- name: rsyslog repository
  tags:
    - rsyslog
    - packages
  apt_repository: repo="ppa:adiscon/v8-stable" update_cache=yes
    
- name: install packages for Debian
  tags:
    - rsyslog
    - packages
  apt: pkg={{item}} state=installed
  with_items: "{{rsyslog_package_names}}"
